export enum FeaturesEnum {
    ItemSeqNumber = 'itemSeqNum',
    Material = 'material',
    ProductName = 'productName',
    Quantity = 'quantity',
    UnitOfMeasure = 'unitOfMeasure',
    GrossPrice = 'grossPrice',
    DeliveryDate = 'deliveryDate',
    DeliveryTime = 'deliveryTime',
    PaymentTerms = 'paymentTerms',
    DischargeTime = 'dischargeTime',
    Application = 'application',
    LoadSize = 'loadSize',
    TimePerLoad = 'timePerLoad',
    TransportMethod = 'transportMethod',
    Slump = 'slump',
    UnloadType = 'unloadType',
    PumpCapacity = 'pumpCapacity',
    Kicker = 'kicker',
    AdditionalServices = 'additionalServices',
    AgreementCode = 'agreementCode',
    AgreementCodePrefix = 'agreementCodePrefix',
    PickupDate = 'pickupDate',
    DeliveryMode = 'deliveryMode'
}
